version: '3.1'

services:
  api:
    build:
      context: .
    restart: unless-stopped
    environment:
      - PORT=${PORT}
      - SECRET_KEY=${SECRET_KEY}
    ports:
      - ${HOST}:${PORT}:${PORT}
    volumes:
      - ./cfg:/app/cfg
