version: '3.1'

services:
  api:
    build:
      context: .
      args:
        - USER_ID=${USER_ID}
        - GROUP_ID=${GROUP_ID}
    restart: always
    environment:
      - ENV=${ENV}
      - DEBUG=${DEBUG}
      - SRV_PATH=/app/srv
      - INTENT_PATH=/app/intent
      - PORT=${PORT}
      - GUNICORN_WORKERS=${GUNICORN_WORKERS}
      - GUNICORN_THREADS=${GUNICORN_THREADS}
      - SECRET_KEY=${SECRET_KEY}
      - SSH_KEY_PRIV=${SSH_KEY_PRIV}
      - SSH_KEY_PUB=${SSH_KEY_PUB}
      - SSH_KNOW_HOSTS=${SSH_KNOW_HOSTS}
      - INTERNAL_API_URL=${INTERNAL_API_URL}
    ports:
      - ${HOST}:${PORT}:${PORT}
    volumes:
      - ./src:/app/src
      - ${SRV_PATH}:/app/srv
      - ${INTENT_PATH}:/app/intent
